// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  production_grid: dynamic(() => import("./ProductionGrid")),
  text_and_image: dynamic(() => import("./TextAndImage")),
  video_block: dynamic(() => import("./VideoBlock")),
};
